<?php
			$optionsArray = array( 'welcome' => array( 'welcomeItems' => array( 'logo' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Alcalde_Chart',
'page' => 'chart' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Presidente_Chart',
'page' => 'chart' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Pres - Por Distrito',
'page' => 'report' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Pres - Por Sector',
'page' => 'report' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Pres - Por Urna',
'page' => 'report' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Alc - Por Distrito',
'page' => 'report' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Alc - Por Sector',
'page' => 'report' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Alc - Por Urna',
'page' => 'report' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'corporacion',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'candidatos',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Dip - Por Orden',
'page' => 'report' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Dip - Resultado Final',
'page' => 'report' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Dashboard',
'page' => 'dashboard' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Urnas - Pendientes',
'page' => 'report' ),
'welcome_item17' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Urnas - Completadas',
'page' => 'report' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'partido',
'page' => 'list' ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'corporaciones',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'estructura',
'page' => 'list' ),
'welcome_item18' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'actas',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'above-grid' => array(  ),
'grid' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item16',
'welcome_item17',
'welcome_item10',
'welcome_item15',
'welcome_item14',
'welcome_item18' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'welcome_item' => 'grid',
'welcome_item1' => 'grid',
'welcome_item2' => 'grid',
'welcome_item3' => 'grid',
'welcome_item4' => 'grid',
'welcome_item5' => 'grid',
'welcome_item6' => 'grid',
'welcome_item7' => 'grid',
'welcome_item8' => 'grid',
'welcome_item9' => 'grid',
'welcome_item11' => 'grid',
'welcome_item12' => 'grid',
'welcome_item13' => 'grid',
'welcome_item16' => 'grid',
'welcome_item17' => 'grid',
'welcome_item10' => 'grid',
'welcome_item15' => 'grid',
'welcome_item14' => 'grid',
'welcome_item18' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'welcome_item' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item16',
'welcome_item17',
'welcome_item15',
'welcome_item18' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'menu-topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item16',
'welcome_item17',
'welcome_item10',
'welcome_item15',
'welcome_item14',
'welcome_item18' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Alcalde_Chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'Alcalde_Chart',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'briefcase' ),
'linkComments' => array( 'text' => 'Alcalde Chart description',
'type' => 0 ),
'background' => '#EDCA00' ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Presidente_Chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'Presidente_Chart',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'barcode' ),
'linkComments' => array( 'text' => 'Presidente Chart description',
'type' => 0 ),
'background' => '#BC8F8F' ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Pres - Por Distrito',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Pres - Por Distrito',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'leaf' ),
'linkComments' => array( 'text' => 'Por Distrito description',
'type' => 0 ),
'background' => '#DC143C' ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Pres - Por Sector',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Pres - Por Sector',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'headphones' ),
'linkComments' => array( 'text' => 'Por Sector description',
'type' => 0 ),
'background' => '#778899' ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Pres - Por Urna',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Pres - Por Urna',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'barcode' ),
'linkComments' => array( 'text' => 'Por Urna description',
'type' => 0 ),
'background' => '#DC143C' ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Alc - Por Distrito',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Alc - Por Distrito',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'barcode' ),
'background' => '#6B8E23' ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Alc - Por Sector',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Alc - Por Sector',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'barcode' ),
'background' => '#E67349' ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Alc - Por Urna',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Alc - Por Urna',
'type' => 6 ),
'background' => '#4169E1' ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'corporacion',
'linkPage' => 'list',
'linkText' => array( 'table' => 'corporacion',
'type' => 6 ),
'background' => '#BC8F8F' ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'candidatos',
'linkPage' => 'list',
'linkText' => array( 'table' => 'candidatos',
'type' => 6 ),
'background' => '#4682B4' ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'partido',
'linkPage' => 'list',
'linkText' => array( 'table' => 'partido',
'type' => 6 ),
'background' => '#CD853F' ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Dip - Por Orden',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Dip - Por Orden',
'type' => 6 ),
'background' => '#EDCA00' ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Dip - Resultado Final',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Dip - Resultado Final',
'type' => 6 ),
'background' => '#9ACD32' ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Dashboard',
'linkPage' => 'dashboard',
'linkText' => array( 'table' => 'Dashboard',
'type' => 6 ),
'background' => '#9ACD32' ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'estructura',
'linkPage' => 'list',
'linkText' => array( 'table' => 'estructura',
'type' => 6 ),
'background' => '#6B8E23' ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Urnas - Pendientes',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Urnas - Pendientes',
'type' => 6 ),
'background' => '#E67349' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'welcome_item17' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Urnas - Completadas',
'linkPage' => 'report',
'linkText' => array( 'table' => 'Urnas - Completadas',
'type' => 6 ),
'background' => '#B22222' ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'corporaciones',
'linkPage' => 'list',
'linkText' => array( 'table' => 'corporaciones',
'type' => 6 ),
'background' => '#CFAE83' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'welcome_item18' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'actas',
'linkPage' => 'list',
'linkText' => array( 'table' => 'actas',
'type' => 6 ),
'background' => '#DB7093' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>