<?php
			$optionsArray = array( 'totals' => array( 'id_partido' => array( 'totalsType' => '' ),
'alcalde' => array( 'totalsType' => '' ),
'vice_alcalde' => array( 'totalsType' => '' ),
'regidor1' => array( 'totalsType' => '' ),
'regidor2' => array( 'totalsType' => '' ),
'regidor3' => array( 'totalsType' => '' ),
'regidor4' => array( 'totalsType' => '' ),
'regidor5' => array( 'totalsType' => '' ),
'regidor6' => array( 'totalsType' => '' ),
'regidor7' => array( 'totalsType' => '' ),
'regidor8' => array( 'totalsType' => '' ),
'regidor9' => array( 'totalsType' => '' ),
'regidor10' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_partido',
'alcalde',
'vice_alcalde',
'regidor1',
'regidor2',
'regidor3',
'regidor4',
'regidor5',
'regidor6',
'regidor7',
'regidor8',
'regidor9',
'regidor10' ),
'exportFields' => array( 'id_partido',
'alcalde',
'vice_alcalde',
'regidor1',
'regidor2',
'regidor3',
'regidor4',
'regidor5',
'regidor6',
'regidor7',
'regidor8',
'regidor9',
'regidor10' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_partido' => array( 'export_field' ),
'alcalde' => array( 'export_field1' ),
'vice_alcalde' => array( 'export_field2' ),
'regidor1' => array( 'export_field3' ),
'regidor2' => array( 'export_field4' ),
'regidor3' => array( 'export_field5' ),
'regidor4' => array( 'export_field6' ),
'regidor5' => array( 'export_field7' ),
'regidor6' => array( 'export_field8' ),
'regidor7' => array( 'export_field9' ),
'regidor8' => array( 'export_field10' ),
'regidor9' => array( 'export_field11' ),
'regidor10' => array( 'export_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id_partido',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'alcalde',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'vice_alcalde',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'regidor1',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'regidor2',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'regidor3',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'regidor4',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'regidor5',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'regidor6',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'regidor7',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'regidor8',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'regidor9',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'regidor10',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>