<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_partido',
'vice_alcalde',
'regidor1',
'regidor2',
'regidor3',
'regidor4',
'regidor5',
'regidor6',
'regidor7',
'regidor8',
'regidor9',
'regidor10',
'alcalde' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_partido' => array( 'import_field' ),
'vice_alcalde' => array( 'import_field1' ),
'regidor1' => array( 'import_field2' ),
'regidor2' => array( 'import_field3' ),
'regidor3' => array( 'import_field4' ),
'regidor4' => array( 'import_field5' ),
'regidor5' => array( 'import_field6' ),
'regidor6' => array( 'import_field7' ),
'regidor7' => array( 'import_field8' ),
'regidor8' => array( 'import_field9' ),
'regidor9' => array( 'import_field10' ),
'regidor10' => array( 'import_field11' ),
'alcalde' => array( 'import_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id_partido',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'vice_alcalde',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'regidor1',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'regidor2',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'regidor3',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'regidor4',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'regidor5',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'regidor6',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'regidor7',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'regidor8',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'regidor9',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'regidor10',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'alcalde',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>