<?php
			$optionsArray = array( 'totals' => array( 'id_urna' => array( 'totalsType' => '' ),
'candidato1' => array( 'totalsType' => '' ),
'candidato2' => array( 'totalsType' => '' ),
'candidato3' => array( 'totalsType' => '' ),
'candidato4' => array( 'totalsType' => '' ),
'candidato5' => array( 'totalsType' => '' ),
'candidato6' => array( 'totalsType' => '' ),
'candidato7' => array( 'totalsType' => '' ),
'candidato8' => array( 'totalsType' => '' ),
'candidato9' => array( 'totalsType' => '' ),
'candidato10' => array( 'totalsType' => '' ),
'candidato11' => array( 'totalsType' => '' ),
'candidato12' => array( 'totalsType' => '' ),
'candidato13' => array( 'totalsType' => '' ),
'candidato14' => array( 'totalsType' => '' ),
'candidato15' => array( 'totalsType' => '' ),
'validos' => array( 'totalsType' => '' ),
'blancos' => array( 'totalsType' => '' ),
'nulos' => array( 'totalsType' => '' ),
'utilizados' => array( 'totalsType' => '' ),
'no_utilizados' => array( 'totalsType' => '' ),
'total' => array( 'totalsType' => '' ),
'usuario' => array( 'totalsType' => '' ),
'fecha' => array( 'totalsType' => '' ),
'editado_por' => array( 'totalsType' => '' ),
'fecha_edicion' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'candidato2',
'candidato3',
'candidato4',
'candidato5',
'candidato6',
'candidato7',
'candidato8',
'candidato9',
'candidato10',
'candidato11',
'candidato12',
'candidato13',
'id_urna',
'candidato1',
'candidato14',
'candidato15',
'validos',
'blancos',
'nulos',
'utilizados',
'no_utilizados',
'total',
'usuario',
'fecha',
'editado_por',
'fecha_edicion' ),
'exportFields' => array( 'id_urna',
'candidato1',
'candidato2',
'candidato3',
'candidato4',
'candidato5',
'candidato6',
'candidato7',
'candidato8',
'candidato9',
'candidato10',
'candidato11',
'candidato12',
'candidato13',
'candidato14',
'candidato15',
'validos',
'blancos',
'nulos',
'utilizados',
'no_utilizados',
'total',
'usuario',
'fecha',
'editado_por',
'fecha_edicion' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'candidato2' => array( 'export_field2' ),
'candidato3' => array( 'export_field3' ),
'candidato4' => array( 'export_field4' ),
'candidato5' => array( 'export_field5' ),
'candidato6' => array( 'export_field6' ),
'candidato7' => array( 'export_field7' ),
'candidato8' => array( 'export_field8' ),
'candidato9' => array( 'export_field9' ),
'candidato10' => array( 'export_field10' ),
'candidato11' => array( 'export_field11' ),
'candidato12' => array( 'export_field12' ),
'candidato13' => array( 'export_field13' ),
'id_urna' => array( 'export_field' ),
'candidato1' => array( 'export_field1' ),
'candidato14' => array( 'export_field14' ),
'candidato15' => array( 'export_field15' ),
'validos' => array( 'export_field16' ),
'blancos' => array( 'export_field17' ),
'nulos' => array( 'export_field18' ),
'utilizados' => array( 'export_field19' ),
'no_utilizados' => array( 'export_field20' ),
'total' => array( 'export_field21' ),
'usuario' => array( 'export_field22' ),
'fecha' => array( 'export_field23' ),
'editado_por' => array( 'export_field24' ),
'fecha_edicion' => array( 'export_field25' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field',
'export_field1',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field2' => array( 'field' => 'candidato2',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'candidato3',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'candidato4',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'candidato5',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'candidato6',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'candidato7',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'candidato8',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'candidato9',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'candidato10',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'candidato11',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'candidato12',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'candidato13',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'id_urna',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'candidato1',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'candidato14',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'candidato15',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'validos',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'blancos',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'nulos',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'utilizados',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'no_utilizados',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'total',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'usuario',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'fecha',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'editado_por',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'fecha_edicion',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>