<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'delete' => true,
'updateSelected' => false,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'master' => array( 'urna' => array( 'preview' => false ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id_urna' => array( 'totalsType' => '' ),
'dip1' => array( 'totalsType' => '' ),
'dip2' => array( 'totalsType' => '' ),
'dip3' => array( 'totalsType' => '' ),
'dip4' => array( 'totalsType' => '' ),
'dip5' => array( 'totalsType' => '' ),
'dip6' => array( 'totalsType' => '' ),
'dip7' => array( 'totalsType' => '' ),
'dip8' => array( 'totalsType' => '' ),
'dip9' => array( 'totalsType' => '' ),
'dip10' => array( 'totalsType' => '' ),
'dip11' => array( 'totalsType' => '' ),
'dip12' => array( 'totalsType' => '' ),
'dip13' => array( 'totalsType' => '' ),
'dip14' => array( 'totalsType' => '' ),
'dip15' => array( 'totalsType' => '' ),
'dip16' => array( 'totalsType' => '' ),
'dip17' => array( 'totalsType' => '' ),
'dip18' => array( 'totalsType' => '' ),
'dip19' => array( 'totalsType' => '' ),
'dip20' => array( 'totalsType' => '' ),
'dip21' => array( 'totalsType' => '' ),
'dip22' => array( 'totalsType' => '' ),
'dip23' => array( 'totalsType' => '' ),
'dip24' => array( 'totalsType' => '' ),
'dip25' => array( 'totalsType' => '' ),
'dip26' => array( 'totalsType' => '' ),
'dip27' => array( 'totalsType' => '' ),
'dip28' => array( 'totalsType' => '' ),
'dip29' => array( 'totalsType' => '' ),
'dip30' => array( 'totalsType' => '' ),
'dip31' => array( 'totalsType' => '' ),
'dip32' => array( 'totalsType' => '' ),
'dip33' => array( 'totalsType' => '' ),
'dip34' => array( 'totalsType' => '' ),
'dip35' => array( 'totalsType' => '' ),
'dip36' => array( 'totalsType' => '' ),
'dip37' => array( 'totalsType' => '' ),
'dip38' => array( 'totalsType' => '' ),
'dip39' => array( 'totalsType' => '' ),
'dip40' => array( 'totalsType' => '' ),
'dip41' => array( 'totalsType' => '' ),
'dip42' => array( 'totalsType' => '' ),
'dip43' => array( 'totalsType' => '' ),
'dip44' => array( 'totalsType' => '' ),
'dip45' => array( 'totalsType' => '' ),
'dip46' => array( 'totalsType' => '' ),
'dip47' => array( 'totalsType' => '' ),
'dip48' => array( 'totalsType' => '' ),
'dip49' => array( 'totalsType' => '' ),
'dip50' => array( 'totalsType' => '' ),
'dip51' => array( 'totalsType' => '' ),
'dip52' => array( 'totalsType' => '' ),
'dip53' => array( 'totalsType' => '' ),
'dip54' => array( 'totalsType' => '' ),
'dip55' => array( 'totalsType' => '' ),
'dip56' => array( 'totalsType' => '' ),
'dip57' => array( 'totalsType' => '' ),
'dip58' => array( 'totalsType' => '' ),
'dip59' => array( 'totalsType' => '' ),
'dip60' => array( 'totalsType' => '' ),
'dip61' => array( 'totalsType' => '' ),
'dip62' => array( 'totalsType' => '' ),
'dip63' => array( 'totalsType' => '' ),
'dip64' => array( 'totalsType' => '' ),
'dip65' => array( 'totalsType' => '' ),
'dip66' => array( 'totalsType' => '' ),
'dip67' => array( 'totalsType' => '' ),
'dip68' => array( 'totalsType' => '' ),
'dip69' => array( 'totalsType' => '' ),
'dip70' => array( 'totalsType' => '' ),
'dip71' => array( 'totalsType' => '' ),
'dip72' => array( 'totalsType' => '' ),
'dip73' => array( 'totalsType' => '' ),
'dip74' => array( 'totalsType' => '' ),
'dip75' => array( 'totalsType' => '' ),
'dip76' => array( 'totalsType' => '' ),
'dip77' => array( 'totalsType' => '' ),
'dip78' => array( 'totalsType' => '' ),
'dip79' => array( 'totalsType' => '' ),
'dip80' => array( 'totalsType' => '' ),
'dip81' => array( 'totalsType' => '' ),
'dip82' => array( 'totalsType' => '' ),
'dip83' => array( 'totalsType' => '' ),
'dip84' => array( 'totalsType' => '' ),
'dip85' => array( 'totalsType' => '' ),
'dip86' => array( 'totalsType' => '' ),
'dip87' => array( 'totalsType' => '' ),
'dip88' => array( 'totalsType' => '' ),
'dip89' => array( 'totalsType' => '' ),
'dip90' => array( 'totalsType' => '' ),
'dip91' => array( 'totalsType' => '' ),
'dip92' => array( 'totalsType' => '' ),
'dip93' => array( 'totalsType' => '' ),
'dip94' => array( 'totalsType' => '' ),
'dip95' => array( 'totalsType' => '' ),
'dip96' => array( 'totalsType' => '' ),
'dip97' => array( 'totalsType' => '' ),
'dip98' => array( 'totalsType' => '' ),
'dip99' => array( 'totalsType' => '' ),
'dip100' => array( 'totalsType' => '' ),
'dip101' => array( 'totalsType' => '' ),
'dip102' => array( 'totalsType' => '' ),
'dip103' => array( 'totalsType' => '' ),
'dip104' => array( 'totalsType' => '' ),
'dip105' => array( 'totalsType' => '' ),
'dip106' => array( 'totalsType' => '' ),
'dip107' => array( 'totalsType' => '' ),
'dip108' => array( 'totalsType' => '' ),
'dip109' => array( 'totalsType' => '' ),
'dip110' => array( 'totalsType' => '' ),
'dip111' => array( 'totalsType' => '' ),
'dip112' => array( 'totalsType' => '' ),
'dip113' => array( 'totalsType' => '' ),
'dip114' => array( 'totalsType' => '' ),
'dip115' => array( 'totalsType' => '' ),
'dip116' => array( 'totalsType' => '' ),
'dip117' => array( 'totalsType' => '' ),
'dip118' => array( 'totalsType' => '' ),
'dip119' => array( 'totalsType' => '' ),
'dip120' => array( 'totalsType' => '' ),
'dip121' => array( 'totalsType' => '' ),
'dip122' => array( 'totalsType' => '' ),
'dip123' => array( 'totalsType' => '' ),
'dip124' => array( 'totalsType' => '' ),
'dip125' => array( 'totalsType' => '' ),
'dip126' => array( 'totalsType' => '' ),
'dip127' => array( 'totalsType' => '' ),
'dip128' => array( 'totalsType' => '' ),
'dip129' => array( 'totalsType' => '' ),
'dip130' => array( 'totalsType' => '' ),
'dip131' => array( 'totalsType' => '' ),
'dip132' => array( 'totalsType' => '' ),
'dip133' => array( 'totalsType' => '' ),
'dip134' => array( 'totalsType' => '' ),
'dip135' => array( 'totalsType' => '' ),
'dip136' => array( 'totalsType' => '' ),
'dip137' => array( 'totalsType' => '' ),
'dip138' => array( 'totalsType' => '' ),
'dip139' => array( 'totalsType' => '' ),
'dip140' => array( 'totalsType' => '' ),
'dip141' => array( 'totalsType' => '' ),
'dip142' => array( 'totalsType' => '' ),
'dip143' => array( 'totalsType' => '' ),
'dip144' => array( 'totalsType' => '' ),
'dip145' => array( 'totalsType' => '' ),
'dip146' => array( 'totalsType' => '' ),
'dip147' => array( 'totalsType' => '' ),
'dip148' => array( 'totalsType' => '' ),
'dip149' => array( 'totalsType' => '' ),
'dip150' => array( 'totalsType' => '' ),
'dip151' => array( 'totalsType' => '' ),
'dip152' => array( 'totalsType' => '' ),
'dip153' => array( 'totalsType' => '' ),
'dip154' => array( 'totalsType' => '' ),
'dip155' => array( 'totalsType' => '' ),
'dip156' => array( 'totalsType' => '' ),
'dip157' => array( 'totalsType' => '' ),
'dip158' => array( 'totalsType' => '' ),
'dip159' => array( 'totalsType' => '' ),
'dip160' => array( 'totalsType' => '' ),
'dip161' => array( 'totalsType' => '' ),
'dip162' => array( 'totalsType' => '' ),
'dip163' => array( 'totalsType' => '' ),
'dip164' => array( 'totalsType' => '' ),
'dip165' => array( 'totalsType' => '' ),
'dip166' => array( 'totalsType' => '' ),
'dip167' => array( 'totalsType' => '' ),
'dip168' => array( 'totalsType' => '' ),
'dip169' => array( 'totalsType' => '' ),
'dip170' => array( 'totalsType' => '' ),
'dip171' => array( 'totalsType' => '' ),
'dip172' => array( 'totalsType' => '' ),
'dip173' => array( 'totalsType' => '' ),
'dip174' => array( 'totalsType' => '' ),
'dip175' => array( 'totalsType' => '' ),
'dip176' => array( 'totalsType' => '' ),
'dip177' => array( 'totalsType' => '' ),
'dip178' => array( 'totalsType' => '' ),
'dip179' => array( 'totalsType' => '' ),
'dip180' => array( 'totalsType' => '' ),
'dip181' => array( 'totalsType' => '' ),
'dip182' => array( 'totalsType' => '' ),
'dip183' => array( 'totalsType' => '' ),
'dip184' => array( 'totalsType' => '' ),
'dip185' => array( 'totalsType' => '' ),
'dip186' => array( 'totalsType' => '' ),
'dip187' => array( 'totalsType' => '' ),
'dip188' => array( 'totalsType' => '' ),
'dip189' => array( 'totalsType' => '' ),
'dip190' => array( 'totalsType' => '' ),
'dip191' => array( 'totalsType' => '' ),
'dip192' => array( 'totalsType' => '' ),
'dip193' => array( 'totalsType' => '' ),
'dip194' => array( 'totalsType' => '' ),
'dip195' => array( 'totalsType' => '' ),
'dip196' => array( 'totalsType' => '' ),
'dip197' => array( 'totalsType' => '' ),
'dip198' => array( 'totalsType' => '' ),
'dip199' => array( 'totalsType' => '' ),
'dip200' => array( 'totalsType' => '' ),
'dip201' => array( 'totalsType' => '' ),
'dip202' => array( 'totalsType' => '' ),
'dip203' => array( 'totalsType' => '' ),
'dip204' => array( 'totalsType' => '' ),
'dip205' => array( 'totalsType' => '' ),
'dip206' => array( 'totalsType' => '' ),
'dip207' => array( 'totalsType' => '' ),
'dip208' => array( 'totalsType' => '' ),
'dip209' => array( 'totalsType' => '' ),
'dip210' => array( 'totalsType' => '' ),
'dip211' => array( 'totalsType' => '' ),
'dip212' => array( 'totalsType' => '' ),
'dip213' => array( 'totalsType' => '' ),
'dip214' => array( 'totalsType' => '' ),
'dip215' => array( 'totalsType' => '' ),
'dip216' => array( 'totalsType' => '' ),
'dip217' => array( 'totalsType' => '' ),
'dip218' => array( 'totalsType' => '' ),
'dip219' => array( 'totalsType' => '' ),
'dip220' => array( 'totalsType' => '' ),
'dip221' => array( 'totalsType' => '' ),
'dip222' => array( 'totalsType' => '' ),
'dip223' => array( 'totalsType' => '' ),
'dip224' => array( 'totalsType' => '' ),
'dip225' => array( 'totalsType' => '' ),
'dip226' => array( 'totalsType' => '' ),
'dip227' => array( 'totalsType' => '' ),
'dip228' => array( 'totalsType' => '' ),
'dip229' => array( 'totalsType' => '' ),
'dip230' => array( 'totalsType' => '' ),
'dip231' => array( 'totalsType' => '' ),
'dip232' => array( 'totalsType' => '' ),
'dip233' => array( 'totalsType' => '' ),
'dip234' => array( 'totalsType' => '' ),
'dip235' => array( 'totalsType' => '' ),
'dip236' => array( 'totalsType' => '' ),
'dip237' => array( 'totalsType' => '' ),
'dip238' => array( 'totalsType' => '' ),
'dip239' => array( 'totalsType' => '' ),
'dip240' => array( 'totalsType' => '' ),
'dip241' => array( 'totalsType' => '' ),
'dip242' => array( 'totalsType' => '' ),
'dip243' => array( 'totalsType' => '' ),
'dip244' => array( 'totalsType' => '' ),
'dip245' => array( 'totalsType' => '' ),
'dip246' => array( 'totalsType' => '' ),
'dip247' => array( 'totalsType' => '' ),
'dip248' => array( 'totalsType' => '' ),
'dip249' => array( 'totalsType' => '' ),
'dip250' => array( 'totalsType' => '' ),
'dip251' => array( 'totalsType' => '' ),
'dip252' => array( 'totalsType' => '' ),
'dip253' => array( 'totalsType' => '' ),
'dip254' => array( 'totalsType' => '' ),
'dip255' => array( 'totalsType' => '' ),
'dip256' => array( 'totalsType' => '' ),
'dip257' => array( 'totalsType' => '' ),
'dip258' => array( 'totalsType' => '' ),
'dip259' => array( 'totalsType' => '' ),
'dip260' => array( 'totalsType' => '' ),
'dip261' => array( 'totalsType' => '' ),
'dip262' => array( 'totalsType' => '' ),
'dip263' => array( 'totalsType' => '' ),
'dip264' => array( 'totalsType' => '' ),
'dip265' => array( 'totalsType' => '' ),
'dip266' => array( 'totalsType' => '' ),
'dip267' => array( 'totalsType' => '' ),
'dip268' => array( 'totalsType' => '' ),
'dip269' => array( 'totalsType' => '' ),
'dip270' => array( 'totalsType' => '' ),
'dip271' => array( 'totalsType' => '' ),
'dip272' => array( 'totalsType' => '' ),
'dip273' => array( 'totalsType' => '' ),
'dip274' => array( 'totalsType' => '' ),
'dip275' => array( 'totalsType' => '' ),
'dip276' => array( 'totalsType' => '' ),
'dip277' => array( 'totalsType' => '' ),
'dip278' => array( 'totalsType' => '' ),
'dip279' => array( 'totalsType' => '' ),
'dip280' => array( 'totalsType' => '' ),
'validos' => array( 'totalsType' => '' ),
'blancos' => array( 'totalsType' => '' ),
'nulos' => array( 'totalsType' => '' ),
'utilizados' => array( 'totalsType' => '' ),
'no_utilizados' => array( 'totalsType' => '' ),
'total' => array( 'totalsType' => '' ),
'usuario' => array( 'totalsType' => '' ),
'fecha' => array( 'totalsType' => '' ),
'editado_por' => array( 'totalsType' => '' ),
'fecha_edicion' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_urna',
'usuario',
'fecha',
'editado_por',
'fecha_edicion' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'editado_por',
'fecha',
'usuario',
'id_urna',
'fecha_edicion' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'id_urna' => array( 'simple_grid_field2',
'simple_grid_field3' ),
'usuario' => array( 'simple_grid_field69',
'simple_grid_field71' ),
'fecha' => array( 'simple_grid_field70',
'simple_grid_field72' ),
'editado_por' => array( 'simple_grid_field',
'simple_grid_field4' ),
'fecha_edicion' => array( 'simple_grid_field1',
'simple_grid_field5' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'add',
'inline_add',
'delete',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field3',
'simple_grid_field2',
'simple_grid_field71',
'simple_grid_field69',
'simple_grid_field72',
'simple_grid_field70',
'simple_grid_field4',
'simple_grid_field',
'simple_grid_field5',
'simple_grid_field1',
'grid_edit',
'grid_inline_cancel',
'grid_view',
'grid_checkbox_head',
'grid_checkbox' ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'inlineadd_link',
'deleteselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'add' => 'above-grid',
'inline_add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field3' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field1' => 'grid',
'grid_edit' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_view' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid' ),
'itemLocations' => array( 'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'delete' => array( 'delete' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'-' => array( '-',
'-1',
'-2' ),
'logo' => array( 'logo1' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'list_options' => array( 'list_options' ),
'delete_selected' => array( 'delete_selected' ),
'search_panel' => array( 'search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'adminarea_link' => array( 'adminarea_link' ),
'grid_field' => array( 'simple_grid_field2',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field',
'simple_grid_field1' ),
'grid_field_label' => array( 'simple_grid_field3',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field4',
'simple_grid_field5' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'id_urna_fieldheadercolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'usuario_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'editado_por_fieldheadercolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_edicion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column',
'inline_cancel',
'view_column' ),
'items' => array( 'grid_edit',
'grid_inline_cancel',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'id_urna_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'usuario_fieldcolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_fieldcolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'editado_por_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_edicion_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 7,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'inline_add',
'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'id_urna',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'id_urna',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'usuario',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'usuario',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'fecha',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'fecha',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'editado_por',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'editado_por',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'fecha_edicion',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'fecha_edicion',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit',
'grid_inline_cancel',
'grid_view' ),
'columnName' => 'list-icons' ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'columnName' => 'checkbox' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'columnName' => 'checkbox' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ),
'columnName' => 'checkbox' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'delete' => array( 'type' => 'delete' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'-' => array( 'type' => '-' ),
'logo1' => array( 'type' => 'logo' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'delete_selected',
'-2',
'show_search_panel',
'hide_search_panel' ) ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'-1' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'search_panel_field' => array( 'field' => 'editado_por',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field1' => array( 'field' => 'fecha_edicion',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'-2' => array( 'type' => '-' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field2' => array( 'field' => 'id_urna',
'type' => 'search_panel_field' ),
'search_panel_field3' => array( 'field' => 'usuario',
'type' => 'search_panel_field' ),
'search_panel_field4' => array( 'field' => 'fecha',
'type' => 'search_panel_field' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'simple_grid_field2' => array( 'field' => 'id_urna',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field3' => array( 'type' => 'grid_field_label',
'field' => 'id_urna' ),
'simple_grid_field69' => array( 'field' => 'usuario',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'usuario' ),
'simple_grid_field70' => array( 'field' => 'fecha',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'fecha' ),
'simple_grid_field' => array( 'field' => 'editado_por',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field4' => array( 'type' => 'grid_field_label',
'field' => 'editado_por' ),
'simple_grid_field1' => array( 'field' => 'fecha_edicion',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'fecha_edicion' ),
'grid_edit' => array( 'type' => 'grid_edit' ),
'grid_view' => array( 'type' => 'grid_view' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4,
'pageWidth' => 'full' );
		?>