<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'usuario',
'dip280',
'dip279',
'dip278',
'dip277',
'dip276',
'dip275',
'dip274',
'dip273',
'dip272',
'dip271',
'dip270',
'dip269',
'dip268',
'dip267',
'dip266',
'dip265',
'dip264',
'dip263',
'dip262',
'dip260',
'dip259',
'dip258',
'dip257',
'dip256',
'dip255',
'dip254',
'dip253',
'dip252',
'dip251',
'dip250',
'dip249',
'dip248',
'dip247',
'dip246',
'dip245',
'dip244',
'dip243',
'dip242',
'dip241',
'dip240',
'dip239',
'dip238',
'dip237',
'dip236',
'dip235',
'dip234',
'dip232',
'dip231',
'dip229',
'dip228',
'dip226',
'dip225',
'dip224',
'dip223',
'dip222',
'dip221',
'dip220',
'dip219',
'dip218',
'dip217',
'dip216',
'dip214',
'dip213',
'dip212',
'dip211',
'dip210',
'dip209',
'dip208',
'dip207',
'dip206',
'dip205',
'dip204',
'dip203',
'dip202',
'dip201',
'dip200',
'dip199',
'dip198',
'dip197',
'dip196',
'dip195',
'dip194',
'dip193',
'dip192',
'dip191',
'dip190',
'dip189',
'dip188',
'dip187',
'dip186',
'dip185',
'dip184',
'dip183',
'dip182',
'dip181',
'dip180',
'dip179',
'dip178',
'dip177',
'dip176',
'dip175',
'dip174',
'dip173',
'dip172',
'dip171',
'dip170',
'dip169',
'dip168',
'dip167',
'dip166',
'dip165',
'dip164',
'dip163',
'dip162',
'dip161',
'dip160',
'dip159',
'dip158',
'dip157',
'dip156',
'dip155',
'dip154',
'dip153',
'dip152',
'dip151',
'dip150',
'dip149',
'dip148',
'dip147',
'dip146',
'dip145',
'dip144',
'dip143',
'dip142',
'dip141',
'dip140',
'dip139',
'dip138',
'dip137',
'dip136',
'dip135',
'dip134',
'dip133',
'dip132',
'dip131',
'dip130',
'dip129',
'dip128',
'dip127',
'dip126',
'dip125',
'dip124',
'dip123',
'dip122',
'dip121',
'dip120',
'dip119',
'dip118',
'dip117',
'dip116',
'dip115',
'dip114',
'dip113',
'dip112',
'dip111',
'dip110',
'dip109',
'dip108',
'dip107',
'dip106',
'dip105',
'dip104',
'dip103',
'dip102',
'dip101',
'dip100',
'dip99',
'dip98',
'dip97',
'dip96',
'dip95',
'dip94',
'dip93',
'dip92',
'dip91',
'dip90',
'dip89',
'dip88',
'dip87',
'dip86',
'dip85',
'dip84',
'dip83',
'dip82',
'dip81',
'dip80',
'dip79',
'dip78',
'dip77',
'dip76',
'dip75',
'dip74',
'dip73',
'dip72',
'dip71',
'dip70',
'dip69',
'dip68',
'dip67',
'dip66',
'dip65',
'dip64',
'dip63',
'dip62',
'dip61',
'id_urna',
'editado_por',
'fecha_edicion' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'usuario' => array( 'integrated_search_field216' ),
'dip280' => array( 'integrated_search_field215' ),
'dip279' => array( 'integrated_search_field214' ),
'dip278' => array( 'integrated_search_field213' ),
'dip277' => array( 'integrated_search_field212' ),
'dip276' => array( 'integrated_search_field211' ),
'dip275' => array( 'integrated_search_field210' ),
'dip274' => array( 'integrated_search_field209' ),
'dip273' => array( 'integrated_search_field208' ),
'dip272' => array( 'integrated_search_field207' ),
'dip271' => array( 'integrated_search_field206' ),
'dip270' => array( 'integrated_search_field205' ),
'dip269' => array( 'integrated_search_field204' ),
'dip268' => array( 'integrated_search_field203' ),
'dip267' => array( 'integrated_search_field202' ),
'dip266' => array( 'integrated_search_field201' ),
'dip265' => array( 'integrated_search_field200' ),
'dip264' => array( 'integrated_search_field199' ),
'dip263' => array( 'integrated_search_field198' ),
'dip262' => array( 'integrated_search_field197' ),
'dip260' => array( 'integrated_search_field196' ),
'dip259' => array( 'integrated_search_field195' ),
'dip258' => array( 'integrated_search_field194' ),
'dip257' => array( 'integrated_search_field193' ),
'dip256' => array( 'integrated_search_field192' ),
'dip255' => array( 'integrated_search_field191' ),
'dip254' => array( 'integrated_search_field190' ),
'dip253' => array( 'integrated_search_field189' ),
'dip252' => array( 'integrated_search_field188' ),
'dip251' => array( 'integrated_search_field187' ),
'dip250' => array( 'integrated_search_field186' ),
'dip249' => array( 'integrated_search_field185' ),
'dip248' => array( 'integrated_search_field184' ),
'dip247' => array( 'integrated_search_field183' ),
'dip246' => array( 'integrated_search_field182' ),
'dip245' => array( 'integrated_search_field181' ),
'dip244' => array( 'integrated_search_field180' ),
'dip243' => array( 'integrated_search_field179' ),
'dip242' => array( 'integrated_search_field178' ),
'dip241' => array( 'integrated_search_field177' ),
'dip240' => array( 'integrated_search_field176' ),
'dip239' => array( 'integrated_search_field175' ),
'dip238' => array( 'integrated_search_field174' ),
'dip237' => array( 'integrated_search_field173' ),
'dip236' => array( 'integrated_search_field172' ),
'dip235' => array( 'integrated_search_field171' ),
'dip234' => array( 'integrated_search_field170' ),
'dip232' => array( 'integrated_search_field169' ),
'dip231' => array( 'integrated_search_field168' ),
'dip229' => array( 'integrated_search_field167' ),
'dip228' => array( 'integrated_search_field166' ),
'dip226' => array( 'integrated_search_field165' ),
'dip225' => array( 'integrated_search_field164' ),
'dip224' => array( 'integrated_search_field163' ),
'dip223' => array( 'integrated_search_field162' ),
'dip222' => array( 'integrated_search_field161' ),
'dip221' => array( 'integrated_search_field160' ),
'dip220' => array( 'integrated_search_field159' ),
'dip219' => array( 'integrated_search_field158' ),
'dip218' => array( 'integrated_search_field157' ),
'dip217' => array( 'integrated_search_field156' ),
'dip216' => array( 'integrated_search_field155' ),
'dip214' => array( 'integrated_search_field154' ),
'dip213' => array( 'integrated_search_field153' ),
'dip212' => array( 'integrated_search_field152' ),
'dip211' => array( 'integrated_search_field151' ),
'dip210' => array( 'integrated_search_field150' ),
'dip209' => array( 'integrated_search_field149' ),
'dip208' => array( 'integrated_search_field148' ),
'dip207' => array( 'integrated_search_field147' ),
'dip206' => array( 'integrated_search_field146' ),
'dip205' => array( 'integrated_search_field145' ),
'dip204' => array( 'integrated_search_field144' ),
'dip203' => array( 'integrated_search_field143' ),
'dip202' => array( 'integrated_search_field142' ),
'dip201' => array( 'integrated_search_field141' ),
'dip200' => array( 'integrated_search_field140' ),
'dip199' => array( 'integrated_search_field139' ),
'dip198' => array( 'integrated_search_field138' ),
'dip197' => array( 'integrated_search_field137' ),
'dip196' => array( 'integrated_search_field136' ),
'dip195' => array( 'integrated_search_field135' ),
'dip194' => array( 'integrated_search_field134' ),
'dip193' => array( 'integrated_search_field133' ),
'dip192' => array( 'integrated_search_field132' ),
'dip191' => array( 'integrated_search_field131' ),
'dip190' => array( 'integrated_search_field130' ),
'dip189' => array( 'integrated_search_field129' ),
'dip188' => array( 'integrated_search_field128' ),
'dip187' => array( 'integrated_search_field127' ),
'dip186' => array( 'integrated_search_field126' ),
'dip185' => array( 'integrated_search_field125' ),
'dip184' => array( 'integrated_search_field124' ),
'dip183' => array( 'integrated_search_field123' ),
'dip182' => array( 'integrated_search_field122' ),
'dip181' => array( 'integrated_search_field121' ),
'dip180' => array( 'integrated_search_field120' ),
'dip179' => array( 'integrated_search_field119' ),
'dip178' => array( 'integrated_search_field118' ),
'dip177' => array( 'integrated_search_field117' ),
'dip176' => array( 'integrated_search_field116' ),
'dip175' => array( 'integrated_search_field115' ),
'dip174' => array( 'integrated_search_field114' ),
'dip173' => array( 'integrated_search_field113' ),
'dip172' => array( 'integrated_search_field112' ),
'dip171' => array( 'integrated_search_field111' ),
'dip170' => array( 'integrated_search_field110' ),
'dip169' => array( 'integrated_search_field109' ),
'dip168' => array( 'integrated_search_field108' ),
'dip167' => array( 'integrated_search_field107' ),
'dip166' => array( 'integrated_search_field106' ),
'dip165' => array( 'integrated_search_field105' ),
'dip164' => array( 'integrated_search_field104' ),
'dip163' => array( 'integrated_search_field103' ),
'dip162' => array( 'integrated_search_field102' ),
'dip161' => array( 'integrated_search_field101' ),
'dip160' => array( 'integrated_search_field100' ),
'dip159' => array( 'integrated_search_field99' ),
'dip158' => array( 'integrated_search_field98' ),
'dip157' => array( 'integrated_search_field97' ),
'dip156' => array( 'integrated_search_field96' ),
'dip155' => array( 'integrated_search_field95' ),
'dip154' => array( 'integrated_search_field94' ),
'dip153' => array( 'integrated_search_field93' ),
'dip152' => array( 'integrated_search_field92' ),
'dip151' => array( 'integrated_search_field91' ),
'dip150' => array( 'integrated_search_field90' ),
'dip149' => array( 'integrated_search_field89' ),
'dip148' => array( 'integrated_search_field88' ),
'dip147' => array( 'integrated_search_field87' ),
'dip146' => array( 'integrated_search_field86' ),
'dip145' => array( 'integrated_search_field85' ),
'dip144' => array( 'integrated_search_field84' ),
'dip143' => array( 'integrated_search_field83' ),
'dip142' => array( 'integrated_search_field82' ),
'dip141' => array( 'integrated_search_field81' ),
'dip140' => array( 'integrated_search_field80' ),
'dip139' => array( 'integrated_search_field79' ),
'dip138' => array( 'integrated_search_field78' ),
'dip137' => array( 'integrated_search_field77' ),
'dip136' => array( 'integrated_search_field76' ),
'dip135' => array( 'integrated_search_field75' ),
'dip134' => array( 'integrated_search_field74' ),
'dip133' => array( 'integrated_search_field73' ),
'dip132' => array( 'integrated_search_field72' ),
'dip131' => array( 'integrated_search_field71' ),
'dip130' => array( 'integrated_search_field70' ),
'dip129' => array( 'integrated_search_field69' ),
'dip128' => array( 'integrated_search_field68' ),
'dip127' => array( 'integrated_search_field67' ),
'dip126' => array( 'integrated_search_field66' ),
'dip125' => array( 'integrated_search_field65' ),
'dip124' => array( 'integrated_search_field64' ),
'dip123' => array( 'integrated_search_field63' ),
'dip122' => array( 'integrated_search_field62' ),
'dip121' => array( 'integrated_search_field61' ),
'dip120' => array( 'integrated_search_field60' ),
'dip119' => array( 'integrated_search_field59' ),
'dip118' => array( 'integrated_search_field58' ),
'dip117' => array( 'integrated_search_field57' ),
'dip116' => array( 'integrated_search_field56' ),
'dip115' => array( 'integrated_search_field55' ),
'dip114' => array( 'integrated_search_field54' ),
'dip113' => array( 'integrated_search_field53' ),
'dip112' => array( 'integrated_search_field52' ),
'dip111' => array( 'integrated_search_field51' ),
'dip110' => array( 'integrated_search_field50' ),
'dip109' => array( 'integrated_search_field49' ),
'dip108' => array( 'integrated_search_field48' ),
'dip107' => array( 'integrated_search_field47' ),
'dip106' => array( 'integrated_search_field46' ),
'dip105' => array( 'integrated_search_field45' ),
'dip104' => array( 'integrated_search_field44' ),
'dip103' => array( 'integrated_search_field43' ),
'dip102' => array( 'integrated_search_field42' ),
'dip101' => array( 'integrated_search_field41' ),
'dip100' => array( 'integrated_search_field40' ),
'dip99' => array( 'integrated_search_field39' ),
'dip98' => array( 'integrated_search_field38' ),
'dip97' => array( 'integrated_search_field37' ),
'dip96' => array( 'integrated_search_field36' ),
'dip95' => array( 'integrated_search_field35' ),
'dip94' => array( 'integrated_search_field34' ),
'dip93' => array( 'integrated_search_field33' ),
'dip92' => array( 'integrated_search_field32' ),
'dip91' => array( 'integrated_search_field31' ),
'dip90' => array( 'integrated_search_field30' ),
'dip89' => array( 'integrated_search_field29' ),
'dip88' => array( 'integrated_search_field28' ),
'dip87' => array( 'integrated_search_field27' ),
'dip86' => array( 'integrated_search_field26' ),
'dip85' => array( 'integrated_search_field25' ),
'dip84' => array( 'integrated_search_field24' ),
'dip83' => array( 'integrated_search_field23' ),
'dip82' => array( 'integrated_search_field22' ),
'dip81' => array( 'integrated_search_field21' ),
'dip80' => array( 'integrated_search_field20' ),
'dip79' => array( 'integrated_search_field19' ),
'dip78' => array( 'integrated_search_field18' ),
'dip77' => array( 'integrated_search_field17' ),
'dip76' => array( 'integrated_search_field16' ),
'dip75' => array( 'integrated_search_field15' ),
'dip74' => array( 'integrated_search_field14' ),
'dip73' => array( 'integrated_search_field13' ),
'dip72' => array( 'integrated_search_field12' ),
'dip71' => array( 'integrated_search_field11' ),
'dip70' => array( 'integrated_search_field10' ),
'dip69' => array( 'integrated_search_field9' ),
'dip68' => array( 'integrated_search_field8' ),
'dip67' => array( 'integrated_search_field7' ),
'dip66' => array( 'integrated_search_field6' ),
'dip65' => array( 'integrated_search_field5' ),
'dip64' => array( 'integrated_search_field4' ),
'dip63' => array( 'integrated_search_field3' ),
'dip62' => array( 'integrated_search_field2' ),
'dip61' => array( 'integrated_search_field1' ),
'id_urna' => array( 'integrated_search_field' ),
'editado_por' => array( 'integrated_search_field217' ),
'fecha_edicion' => array( 'integrated_search_field218' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field89',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94',
'integrated_search_field95',
'integrated_search_field96',
'integrated_search_field97',
'integrated_search_field98',
'integrated_search_field99',
'integrated_search_field100',
'integrated_search_field101',
'integrated_search_field102',
'integrated_search_field103',
'integrated_search_field104',
'integrated_search_field105',
'integrated_search_field106',
'integrated_search_field107',
'integrated_search_field108',
'integrated_search_field109',
'integrated_search_field110',
'integrated_search_field111',
'integrated_search_field112',
'integrated_search_field113',
'integrated_search_field114',
'integrated_search_field115',
'integrated_search_field116',
'integrated_search_field117',
'integrated_search_field118',
'integrated_search_field119',
'integrated_search_field120',
'integrated_search_field121',
'integrated_search_field122',
'integrated_search_field123',
'integrated_search_field124',
'integrated_search_field125',
'integrated_search_field126',
'integrated_search_field127',
'integrated_search_field128',
'integrated_search_field129',
'integrated_search_field130',
'integrated_search_field131',
'integrated_search_field132',
'integrated_search_field133',
'integrated_search_field134',
'integrated_search_field135',
'integrated_search_field136',
'integrated_search_field137',
'integrated_search_field138',
'integrated_search_field139',
'integrated_search_field140',
'integrated_search_field141',
'integrated_search_field142',
'integrated_search_field143',
'integrated_search_field144',
'integrated_search_field145',
'integrated_search_field146',
'integrated_search_field147',
'integrated_search_field148',
'integrated_search_field149',
'integrated_search_field150',
'integrated_search_field151',
'integrated_search_field152',
'integrated_search_field153',
'integrated_search_field154',
'integrated_search_field155',
'integrated_search_field156',
'integrated_search_field157',
'integrated_search_field158',
'integrated_search_field159',
'integrated_search_field160',
'integrated_search_field161',
'integrated_search_field162',
'integrated_search_field163',
'integrated_search_field164',
'integrated_search_field165',
'integrated_search_field166',
'integrated_search_field167',
'integrated_search_field168',
'integrated_search_field169',
'integrated_search_field170',
'integrated_search_field171',
'integrated_search_field172',
'integrated_search_field173',
'integrated_search_field174',
'integrated_search_field175',
'integrated_search_field176',
'integrated_search_field177',
'integrated_search_field178',
'integrated_search_field179',
'integrated_search_field180',
'integrated_search_field181',
'integrated_search_field182',
'integrated_search_field183',
'integrated_search_field184',
'integrated_search_field185',
'integrated_search_field186',
'integrated_search_field187',
'integrated_search_field188',
'integrated_search_field189',
'integrated_search_field190',
'integrated_search_field191',
'integrated_search_field192',
'integrated_search_field193',
'integrated_search_field194',
'integrated_search_field195',
'integrated_search_field196',
'integrated_search_field197',
'integrated_search_field198',
'integrated_search_field199',
'integrated_search_field200',
'integrated_search_field201',
'integrated_search_field202',
'integrated_search_field203',
'integrated_search_field204',
'integrated_search_field205',
'integrated_search_field206',
'integrated_search_field207',
'integrated_search_field208',
'integrated_search_field209',
'integrated_search_field210',
'integrated_search_field211',
'integrated_search_field212',
'integrated_search_field213',
'integrated_search_field214',
'integrated_search_field215',
'integrated_search_field216',
'integrated_search_field217',
'integrated_search_field218' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid',
'integrated_search_field41' => 'grid',
'integrated_search_field42' => 'grid',
'integrated_search_field43' => 'grid',
'integrated_search_field44' => 'grid',
'integrated_search_field45' => 'grid',
'integrated_search_field46' => 'grid',
'integrated_search_field47' => 'grid',
'integrated_search_field48' => 'grid',
'integrated_search_field49' => 'grid',
'integrated_search_field50' => 'grid',
'integrated_search_field51' => 'grid',
'integrated_search_field52' => 'grid',
'integrated_search_field53' => 'grid',
'integrated_search_field54' => 'grid',
'integrated_search_field55' => 'grid',
'integrated_search_field56' => 'grid',
'integrated_search_field57' => 'grid',
'integrated_search_field58' => 'grid',
'integrated_search_field59' => 'grid',
'integrated_search_field60' => 'grid',
'integrated_search_field61' => 'grid',
'integrated_search_field62' => 'grid',
'integrated_search_field63' => 'grid',
'integrated_search_field64' => 'grid',
'integrated_search_field65' => 'grid',
'integrated_search_field66' => 'grid',
'integrated_search_field67' => 'grid',
'integrated_search_field68' => 'grid',
'integrated_search_field69' => 'grid',
'integrated_search_field70' => 'grid',
'integrated_search_field71' => 'grid',
'integrated_search_field72' => 'grid',
'integrated_search_field73' => 'grid',
'integrated_search_field74' => 'grid',
'integrated_search_field75' => 'grid',
'integrated_search_field76' => 'grid',
'integrated_search_field77' => 'grid',
'integrated_search_field78' => 'grid',
'integrated_search_field79' => 'grid',
'integrated_search_field80' => 'grid',
'integrated_search_field81' => 'grid',
'integrated_search_field82' => 'grid',
'integrated_search_field83' => 'grid',
'integrated_search_field84' => 'grid',
'integrated_search_field85' => 'grid',
'integrated_search_field86' => 'grid',
'integrated_search_field87' => 'grid',
'integrated_search_field88' => 'grid',
'integrated_search_field89' => 'grid',
'integrated_search_field90' => 'grid',
'integrated_search_field91' => 'grid',
'integrated_search_field92' => 'grid',
'integrated_search_field93' => 'grid',
'integrated_search_field94' => 'grid',
'integrated_search_field95' => 'grid',
'integrated_search_field96' => 'grid',
'integrated_search_field97' => 'grid',
'integrated_search_field98' => 'grid',
'integrated_search_field99' => 'grid',
'integrated_search_field100' => 'grid',
'integrated_search_field101' => 'grid',
'integrated_search_field102' => 'grid',
'integrated_search_field103' => 'grid',
'integrated_search_field104' => 'grid',
'integrated_search_field105' => 'grid',
'integrated_search_field106' => 'grid',
'integrated_search_field107' => 'grid',
'integrated_search_field108' => 'grid',
'integrated_search_field109' => 'grid',
'integrated_search_field110' => 'grid',
'integrated_search_field111' => 'grid',
'integrated_search_field112' => 'grid',
'integrated_search_field113' => 'grid',
'integrated_search_field114' => 'grid',
'integrated_search_field115' => 'grid',
'integrated_search_field116' => 'grid',
'integrated_search_field117' => 'grid',
'integrated_search_field118' => 'grid',
'integrated_search_field119' => 'grid',
'integrated_search_field120' => 'grid',
'integrated_search_field121' => 'grid',
'integrated_search_field122' => 'grid',
'integrated_search_field123' => 'grid',
'integrated_search_field124' => 'grid',
'integrated_search_field125' => 'grid',
'integrated_search_field126' => 'grid',
'integrated_search_field127' => 'grid',
'integrated_search_field128' => 'grid',
'integrated_search_field129' => 'grid',
'integrated_search_field130' => 'grid',
'integrated_search_field131' => 'grid',
'integrated_search_field132' => 'grid',
'integrated_search_field133' => 'grid',
'integrated_search_field134' => 'grid',
'integrated_search_field135' => 'grid',
'integrated_search_field136' => 'grid',
'integrated_search_field137' => 'grid',
'integrated_search_field138' => 'grid',
'integrated_search_field139' => 'grid',
'integrated_search_field140' => 'grid',
'integrated_search_field141' => 'grid',
'integrated_search_field142' => 'grid',
'integrated_search_field143' => 'grid',
'integrated_search_field144' => 'grid',
'integrated_search_field145' => 'grid',
'integrated_search_field146' => 'grid',
'integrated_search_field147' => 'grid',
'integrated_search_field148' => 'grid',
'integrated_search_field149' => 'grid',
'integrated_search_field150' => 'grid',
'integrated_search_field151' => 'grid',
'integrated_search_field152' => 'grid',
'integrated_search_field153' => 'grid',
'integrated_search_field154' => 'grid',
'integrated_search_field155' => 'grid',
'integrated_search_field156' => 'grid',
'integrated_search_field157' => 'grid',
'integrated_search_field158' => 'grid',
'integrated_search_field159' => 'grid',
'integrated_search_field160' => 'grid',
'integrated_search_field161' => 'grid',
'integrated_search_field162' => 'grid',
'integrated_search_field163' => 'grid',
'integrated_search_field164' => 'grid',
'integrated_search_field165' => 'grid',
'integrated_search_field166' => 'grid',
'integrated_search_field167' => 'grid',
'integrated_search_field168' => 'grid',
'integrated_search_field169' => 'grid',
'integrated_search_field170' => 'grid',
'integrated_search_field171' => 'grid',
'integrated_search_field172' => 'grid',
'integrated_search_field173' => 'grid',
'integrated_search_field174' => 'grid',
'integrated_search_field175' => 'grid',
'integrated_search_field176' => 'grid',
'integrated_search_field177' => 'grid',
'integrated_search_field178' => 'grid',
'integrated_search_field179' => 'grid',
'integrated_search_field180' => 'grid',
'integrated_search_field181' => 'grid',
'integrated_search_field182' => 'grid',
'integrated_search_field183' => 'grid',
'integrated_search_field184' => 'grid',
'integrated_search_field185' => 'grid',
'integrated_search_field186' => 'grid',
'integrated_search_field187' => 'grid',
'integrated_search_field188' => 'grid',
'integrated_search_field189' => 'grid',
'integrated_search_field190' => 'grid',
'integrated_search_field191' => 'grid',
'integrated_search_field192' => 'grid',
'integrated_search_field193' => 'grid',
'integrated_search_field194' => 'grid',
'integrated_search_field195' => 'grid',
'integrated_search_field196' => 'grid',
'integrated_search_field197' => 'grid',
'integrated_search_field198' => 'grid',
'integrated_search_field199' => 'grid',
'integrated_search_field200' => 'grid',
'integrated_search_field201' => 'grid',
'integrated_search_field202' => 'grid',
'integrated_search_field203' => 'grid',
'integrated_search_field204' => 'grid',
'integrated_search_field205' => 'grid',
'integrated_search_field206' => 'grid',
'integrated_search_field207' => 'grid',
'integrated_search_field208' => 'grid',
'integrated_search_field209' => 'grid',
'integrated_search_field210' => 'grid',
'integrated_search_field211' => 'grid',
'integrated_search_field212' => 'grid',
'integrated_search_field213' => 'grid',
'integrated_search_field214' => 'grid',
'integrated_search_field215' => 'grid',
'integrated_search_field216' => 'grid',
'integrated_search_field217' => 'grid',
'integrated_search_field218' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field42' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field43' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field44' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field47' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field48' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field49' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field50' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field51' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field52' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field53' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field54' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field55' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field56' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field57' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field58' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field59' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field60' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field61' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field62' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field63' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field64' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field65' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field66' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field67' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field68' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field69' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field70' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field71' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field72' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field73' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field74' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field75' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field76' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field77' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field78' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field79' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field80' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field81' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field82' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field83' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field84' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field85' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field86' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field87' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field88' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field89' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field90' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field91' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field92' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field93' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field94' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field95' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field96' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field97' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field98' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field99' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field100' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field101' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field102' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field103' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field104' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field105' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field106' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field107' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field108' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field109' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field110' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field111' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field112' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field113' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field114' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field115' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field116' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field117' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field118' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field119' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field120' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field121' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field122' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field123' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field124' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field125' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field126' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field127' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field128' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field129' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field130' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field131' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field132' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field133' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field134' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field135' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field136' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field137' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field138' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field139' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field140' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field141' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field142' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field143' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field144' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field145' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field146' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field147' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field148' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field149' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field150' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field151' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field152' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field153' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field154' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field155' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field156' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field157' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field158' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field159' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field160' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field161' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field162' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field163' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field164' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field165' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field166' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field167' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field168' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field169' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field170' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field171' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field172' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field173' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field174' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field175' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field176' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field177' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field178' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field179' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field180' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field181' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field182' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field183' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field184' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field185' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field186' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field187' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field188' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field189' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field190' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field191' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field192' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field193' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field194' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field195' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field196' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field197' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field198' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field199' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field200' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field201' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field202' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field203' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field204' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field205' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field206' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field207' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field208' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field209' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field210' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field211' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field212' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field213' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field214' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field215' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field216' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field217' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field218' => array( 'location' => 'grid',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field216',
'integrated_search_field215',
'integrated_search_field214',
'integrated_search_field213',
'integrated_search_field212',
'integrated_search_field211',
'integrated_search_field210',
'integrated_search_field209',
'integrated_search_field208',
'integrated_search_field207',
'integrated_search_field206',
'integrated_search_field205',
'integrated_search_field204',
'integrated_search_field203',
'integrated_search_field202',
'integrated_search_field201',
'integrated_search_field200',
'integrated_search_field199',
'integrated_search_field198',
'integrated_search_field197',
'integrated_search_field196',
'integrated_search_field195',
'integrated_search_field194',
'integrated_search_field193',
'integrated_search_field192',
'integrated_search_field191',
'integrated_search_field190',
'integrated_search_field189',
'integrated_search_field188',
'integrated_search_field187',
'integrated_search_field186',
'integrated_search_field185',
'integrated_search_field184',
'integrated_search_field183',
'integrated_search_field182',
'integrated_search_field181',
'integrated_search_field180',
'integrated_search_field179',
'integrated_search_field178',
'integrated_search_field177',
'integrated_search_field176',
'integrated_search_field175',
'integrated_search_field174',
'integrated_search_field173',
'integrated_search_field172',
'integrated_search_field171',
'integrated_search_field170',
'integrated_search_field169',
'integrated_search_field168',
'integrated_search_field167',
'integrated_search_field166',
'integrated_search_field165',
'integrated_search_field164',
'integrated_search_field163',
'integrated_search_field162',
'integrated_search_field161',
'integrated_search_field160',
'integrated_search_field159',
'integrated_search_field158',
'integrated_search_field157',
'integrated_search_field156',
'integrated_search_field155',
'integrated_search_field154',
'integrated_search_field153',
'integrated_search_field152',
'integrated_search_field151',
'integrated_search_field150',
'integrated_search_field149',
'integrated_search_field148',
'integrated_search_field147',
'integrated_search_field146',
'integrated_search_field145',
'integrated_search_field144',
'integrated_search_field143',
'integrated_search_field142',
'integrated_search_field141',
'integrated_search_field140',
'integrated_search_field139',
'integrated_search_field138',
'integrated_search_field137',
'integrated_search_field136',
'integrated_search_field135',
'integrated_search_field134',
'integrated_search_field133',
'integrated_search_field132',
'integrated_search_field131',
'integrated_search_field130',
'integrated_search_field129',
'integrated_search_field128',
'integrated_search_field127',
'integrated_search_field126',
'integrated_search_field125',
'integrated_search_field124',
'integrated_search_field123',
'integrated_search_field122',
'integrated_search_field121',
'integrated_search_field120',
'integrated_search_field119',
'integrated_search_field118',
'integrated_search_field117',
'integrated_search_field116',
'integrated_search_field115',
'integrated_search_field114',
'integrated_search_field113',
'integrated_search_field112',
'integrated_search_field111',
'integrated_search_field110',
'integrated_search_field109',
'integrated_search_field108',
'integrated_search_field107',
'integrated_search_field106',
'integrated_search_field105',
'integrated_search_field104',
'integrated_search_field103',
'integrated_search_field102',
'integrated_search_field101',
'integrated_search_field100',
'integrated_search_field99',
'integrated_search_field98',
'integrated_search_field97',
'integrated_search_field96',
'integrated_search_field95',
'integrated_search_field94',
'integrated_search_field93',
'integrated_search_field92',
'integrated_search_field91',
'integrated_search_field90',
'integrated_search_field89',
'integrated_search_field88',
'integrated_search_field87',
'integrated_search_field86',
'integrated_search_field85',
'integrated_search_field84',
'integrated_search_field83',
'integrated_search_field82',
'integrated_search_field81',
'integrated_search_field80',
'integrated_search_field79',
'integrated_search_field78',
'integrated_search_field77',
'integrated_search_field76',
'integrated_search_field75',
'integrated_search_field74',
'integrated_search_field73',
'integrated_search_field72',
'integrated_search_field71',
'integrated_search_field70',
'integrated_search_field69',
'integrated_search_field68',
'integrated_search_field67',
'integrated_search_field66',
'integrated_search_field65',
'integrated_search_field64',
'integrated_search_field63',
'integrated_search_field62',
'integrated_search_field61',
'integrated_search_field60',
'integrated_search_field59',
'integrated_search_field58',
'integrated_search_field57',
'integrated_search_field56',
'integrated_search_field55',
'integrated_search_field54',
'integrated_search_field53',
'integrated_search_field52',
'integrated_search_field51',
'integrated_search_field50',
'integrated_search_field49',
'integrated_search_field48',
'integrated_search_field47',
'integrated_search_field46',
'integrated_search_field45',
'integrated_search_field44',
'integrated_search_field43',
'integrated_search_field42',
'integrated_search_field41',
'integrated_search_field40',
'integrated_search_field39',
'integrated_search_field38',
'integrated_search_field37',
'integrated_search_field36',
'integrated_search_field35',
'integrated_search_field34',
'integrated_search_field33',
'integrated_search_field32',
'integrated_search_field31',
'integrated_search_field30',
'integrated_search_field29',
'integrated_search_field28',
'integrated_search_field27',
'integrated_search_field26',
'integrated_search_field25',
'integrated_search_field24',
'integrated_search_field23',
'integrated_search_field22',
'integrated_search_field21',
'integrated_search_field20',
'integrated_search_field19',
'integrated_search_field18',
'integrated_search_field17',
'integrated_search_field16',
'integrated_search_field15',
'integrated_search_field14',
'integrated_search_field13',
'integrated_search_field12',
'integrated_search_field11',
'integrated_search_field10',
'integrated_search_field9',
'integrated_search_field8',
'integrated_search_field7',
'integrated_search_field6',
'integrated_search_field5',
'integrated_search_field4',
'integrated_search_field3',
'integrated_search_field2',
'integrated_search_field1',
'integrated_search_field',
'integrated_search_field217',
'integrated_search_field218' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field89',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94',
'integrated_search_field95',
'integrated_search_field96',
'integrated_search_field97',
'integrated_search_field98',
'integrated_search_field99',
'integrated_search_field100',
'integrated_search_field101',
'integrated_search_field102',
'integrated_search_field103',
'integrated_search_field104',
'integrated_search_field105',
'integrated_search_field106',
'integrated_search_field107',
'integrated_search_field108',
'integrated_search_field109',
'integrated_search_field110',
'integrated_search_field111',
'integrated_search_field112',
'integrated_search_field113',
'integrated_search_field114',
'integrated_search_field115',
'integrated_search_field116',
'integrated_search_field117',
'integrated_search_field118',
'integrated_search_field119',
'integrated_search_field120',
'integrated_search_field121',
'integrated_search_field122',
'integrated_search_field123',
'integrated_search_field124',
'integrated_search_field125',
'integrated_search_field126',
'integrated_search_field127',
'integrated_search_field128',
'integrated_search_field129',
'integrated_search_field130',
'integrated_search_field131',
'integrated_search_field132',
'integrated_search_field133',
'integrated_search_field134',
'integrated_search_field135',
'integrated_search_field136',
'integrated_search_field137',
'integrated_search_field138',
'integrated_search_field139',
'integrated_search_field140',
'integrated_search_field141',
'integrated_search_field142',
'integrated_search_field143',
'integrated_search_field144',
'integrated_search_field145',
'integrated_search_field146',
'integrated_search_field147',
'integrated_search_field148',
'integrated_search_field149',
'integrated_search_field150',
'integrated_search_field151',
'integrated_search_field152',
'integrated_search_field153',
'integrated_search_field154',
'integrated_search_field155',
'integrated_search_field156',
'integrated_search_field157',
'integrated_search_field158',
'integrated_search_field159',
'integrated_search_field160',
'integrated_search_field161',
'integrated_search_field162',
'integrated_search_field163',
'integrated_search_field164',
'integrated_search_field165',
'integrated_search_field166',
'integrated_search_field167',
'integrated_search_field168',
'integrated_search_field169',
'integrated_search_field170',
'integrated_search_field171',
'integrated_search_field172',
'integrated_search_field173',
'integrated_search_field174',
'integrated_search_field175',
'integrated_search_field176',
'integrated_search_field177',
'integrated_search_field178',
'integrated_search_field179',
'integrated_search_field180',
'integrated_search_field181',
'integrated_search_field182',
'integrated_search_field183',
'integrated_search_field184',
'integrated_search_field185',
'integrated_search_field186',
'integrated_search_field187',
'integrated_search_field188',
'integrated_search_field189',
'integrated_search_field190',
'integrated_search_field191',
'integrated_search_field192',
'integrated_search_field193',
'integrated_search_field194',
'integrated_search_field195',
'integrated_search_field196',
'integrated_search_field197',
'integrated_search_field198',
'integrated_search_field199',
'integrated_search_field200',
'integrated_search_field201',
'integrated_search_field202',
'integrated_search_field203',
'integrated_search_field204',
'integrated_search_field205',
'integrated_search_field206',
'integrated_search_field207',
'integrated_search_field208',
'integrated_search_field209',
'integrated_search_field210',
'integrated_search_field211',
'integrated_search_field212',
'integrated_search_field213',
'integrated_search_field214',
'integrated_search_field215',
'integrated_search_field216',
'integrated_search_field217',
'integrated_search_field218' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field89',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94',
'integrated_search_field95',
'integrated_search_field96',
'integrated_search_field97',
'integrated_search_field98',
'integrated_search_field99',
'integrated_search_field100',
'integrated_search_field101',
'integrated_search_field102',
'integrated_search_field103',
'integrated_search_field104',
'integrated_search_field105',
'integrated_search_field106',
'integrated_search_field107',
'integrated_search_field108',
'integrated_search_field109',
'integrated_search_field110',
'integrated_search_field111',
'integrated_search_field112',
'integrated_search_field113',
'integrated_search_field114',
'integrated_search_field115',
'integrated_search_field116',
'integrated_search_field117',
'integrated_search_field118',
'integrated_search_field119',
'integrated_search_field120',
'integrated_search_field121',
'integrated_search_field122',
'integrated_search_field123',
'integrated_search_field124',
'integrated_search_field125',
'integrated_search_field126',
'integrated_search_field127',
'integrated_search_field128',
'integrated_search_field129',
'integrated_search_field130',
'integrated_search_field131',
'integrated_search_field132',
'integrated_search_field133',
'integrated_search_field134',
'integrated_search_field135',
'integrated_search_field136',
'integrated_search_field137',
'integrated_search_field138',
'integrated_search_field139',
'integrated_search_field140',
'integrated_search_field141',
'integrated_search_field142',
'integrated_search_field143',
'integrated_search_field144',
'integrated_search_field145',
'integrated_search_field146',
'integrated_search_field147',
'integrated_search_field148',
'integrated_search_field149',
'integrated_search_field150',
'integrated_search_field151',
'integrated_search_field152',
'integrated_search_field153',
'integrated_search_field154',
'integrated_search_field155',
'integrated_search_field156',
'integrated_search_field157',
'integrated_search_field158',
'integrated_search_field159',
'integrated_search_field160',
'integrated_search_field161',
'integrated_search_field162',
'integrated_search_field163',
'integrated_search_field164',
'integrated_search_field165',
'integrated_search_field166',
'integrated_search_field167',
'integrated_search_field168',
'integrated_search_field169',
'integrated_search_field170',
'integrated_search_field171',
'integrated_search_field172',
'integrated_search_field173',
'integrated_search_field174',
'integrated_search_field175',
'integrated_search_field176',
'integrated_search_field177',
'integrated_search_field178',
'integrated_search_field179',
'integrated_search_field180',
'integrated_search_field181',
'integrated_search_field182',
'integrated_search_field183',
'integrated_search_field184',
'integrated_search_field185',
'integrated_search_field186',
'integrated_search_field187',
'integrated_search_field188',
'integrated_search_field189',
'integrated_search_field190',
'integrated_search_field191',
'integrated_search_field192',
'integrated_search_field193',
'integrated_search_field194',
'integrated_search_field195',
'integrated_search_field196',
'integrated_search_field197',
'integrated_search_field198',
'integrated_search_field199',
'integrated_search_field200',
'integrated_search_field201',
'integrated_search_field202',
'integrated_search_field203',
'integrated_search_field204',
'integrated_search_field205',
'integrated_search_field206',
'integrated_search_field207',
'integrated_search_field208',
'integrated_search_field209',
'integrated_search_field210',
'integrated_search_field211',
'integrated_search_field212',
'integrated_search_field213',
'integrated_search_field214',
'integrated_search_field215',
'integrated_search_field216',
'integrated_search_field217',
'integrated_search_field218' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field216' => array( 'field' => 'usuario',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field215' => array( 'field' => 'dip280',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field214' => array( 'field' => 'dip279',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field213' => array( 'field' => 'dip278',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field212' => array( 'field' => 'dip277',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field211' => array( 'field' => 'dip276',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field210' => array( 'field' => 'dip275',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field209' => array( 'field' => 'dip274',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field208' => array( 'field' => 'dip273',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field207' => array( 'field' => 'dip272',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field206' => array( 'field' => 'dip271',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field205' => array( 'field' => 'dip270',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field204' => array( 'field' => 'dip269',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field203' => array( 'field' => 'dip268',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field202' => array( 'field' => 'dip267',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field201' => array( 'field' => 'dip266',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field200' => array( 'field' => 'dip265',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field199' => array( 'field' => 'dip264',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field198' => array( 'field' => 'dip263',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field197' => array( 'field' => 'dip262',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field196' => array( 'field' => 'dip260',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field195' => array( 'field' => 'dip259',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field194' => array( 'field' => 'dip258',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field193' => array( 'field' => 'dip257',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field192' => array( 'field' => 'dip256',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field191' => array( 'field' => 'dip255',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field190' => array( 'field' => 'dip254',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field189' => array( 'field' => 'dip253',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field188' => array( 'field' => 'dip252',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field187' => array( 'field' => 'dip251',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field186' => array( 'field' => 'dip250',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field185' => array( 'field' => 'dip249',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field184' => array( 'field' => 'dip248',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field183' => array( 'field' => 'dip247',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field182' => array( 'field' => 'dip246',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field181' => array( 'field' => 'dip245',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field180' => array( 'field' => 'dip244',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field179' => array( 'field' => 'dip243',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field178' => array( 'field' => 'dip242',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field177' => array( 'field' => 'dip241',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field176' => array( 'field' => 'dip240',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field175' => array( 'field' => 'dip239',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field174' => array( 'field' => 'dip238',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field173' => array( 'field' => 'dip237',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field172' => array( 'field' => 'dip236',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field171' => array( 'field' => 'dip235',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field170' => array( 'field' => 'dip234',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field169' => array( 'field' => 'dip232',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field168' => array( 'field' => 'dip231',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field167' => array( 'field' => 'dip229',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field166' => array( 'field' => 'dip228',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field165' => array( 'field' => 'dip226',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field164' => array( 'field' => 'dip225',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field163' => array( 'field' => 'dip224',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field162' => array( 'field' => 'dip223',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field161' => array( 'field' => 'dip222',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field160' => array( 'field' => 'dip221',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field159' => array( 'field' => 'dip220',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field158' => array( 'field' => 'dip219',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field157' => array( 'field' => 'dip218',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field156' => array( 'field' => 'dip217',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field155' => array( 'field' => 'dip216',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field154' => array( 'field' => 'dip214',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field153' => array( 'field' => 'dip213',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field152' => array( 'field' => 'dip212',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field151' => array( 'field' => 'dip211',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field150' => array( 'field' => 'dip210',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field149' => array( 'field' => 'dip209',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field148' => array( 'field' => 'dip208',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field147' => array( 'field' => 'dip207',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field146' => array( 'field' => 'dip206',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field145' => array( 'field' => 'dip205',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field144' => array( 'field' => 'dip204',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field143' => array( 'field' => 'dip203',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field142' => array( 'field' => 'dip202',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field141' => array( 'field' => 'dip201',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field140' => array( 'field' => 'dip200',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field139' => array( 'field' => 'dip199',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field138' => array( 'field' => 'dip198',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field137' => array( 'field' => 'dip197',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field136' => array( 'field' => 'dip196',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field135' => array( 'field' => 'dip195',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field134' => array( 'field' => 'dip194',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field133' => array( 'field' => 'dip193',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field132' => array( 'field' => 'dip192',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field131' => array( 'field' => 'dip191',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field130' => array( 'field' => 'dip190',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field129' => array( 'field' => 'dip189',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field128' => array( 'field' => 'dip188',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field127' => array( 'field' => 'dip187',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field126' => array( 'field' => 'dip186',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field125' => array( 'field' => 'dip185',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field124' => array( 'field' => 'dip184',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field123' => array( 'field' => 'dip183',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field122' => array( 'field' => 'dip182',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field121' => array( 'field' => 'dip181',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field120' => array( 'field' => 'dip180',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field119' => array( 'field' => 'dip179',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field118' => array( 'field' => 'dip178',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field117' => array( 'field' => 'dip177',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field116' => array( 'field' => 'dip176',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field115' => array( 'field' => 'dip175',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field114' => array( 'field' => 'dip174',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field113' => array( 'field' => 'dip173',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field112' => array( 'field' => 'dip172',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field111' => array( 'field' => 'dip171',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field110' => array( 'field' => 'dip170',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field109' => array( 'field' => 'dip169',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field108' => array( 'field' => 'dip168',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field107' => array( 'field' => 'dip167',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field106' => array( 'field' => 'dip166',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field105' => array( 'field' => 'dip165',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field104' => array( 'field' => 'dip164',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field103' => array( 'field' => 'dip163',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field102' => array( 'field' => 'dip162',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field101' => array( 'field' => 'dip161',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field100' => array( 'field' => 'dip160',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field99' => array( 'field' => 'dip159',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field98' => array( 'field' => 'dip158',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field97' => array( 'field' => 'dip157',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field96' => array( 'field' => 'dip156',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field95' => array( 'field' => 'dip155',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field94' => array( 'field' => 'dip154',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field93' => array( 'field' => 'dip153',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field92' => array( 'field' => 'dip152',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field91' => array( 'field' => 'dip151',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field90' => array( 'field' => 'dip150',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field89' => array( 'field' => 'dip149',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field88' => array( 'field' => 'dip148',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field87' => array( 'field' => 'dip147',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field86' => array( 'field' => 'dip146',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field85' => array( 'field' => 'dip145',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field84' => array( 'field' => 'dip144',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field83' => array( 'field' => 'dip143',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field82' => array( 'field' => 'dip142',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field81' => array( 'field' => 'dip141',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field80' => array( 'field' => 'dip140',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field79' => array( 'field' => 'dip139',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field78' => array( 'field' => 'dip138',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field77' => array( 'field' => 'dip137',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field76' => array( 'field' => 'dip136',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field75' => array( 'field' => 'dip135',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field74' => array( 'field' => 'dip134',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field73' => array( 'field' => 'dip133',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field72' => array( 'field' => 'dip132',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field71' => array( 'field' => 'dip131',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field70' => array( 'field' => 'dip130',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field69' => array( 'field' => 'dip129',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field68' => array( 'field' => 'dip128',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field67' => array( 'field' => 'dip127',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field66' => array( 'field' => 'dip126',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field65' => array( 'field' => 'dip125',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field64' => array( 'field' => 'dip124',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field63' => array( 'field' => 'dip123',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field62' => array( 'field' => 'dip122',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field61' => array( 'field' => 'dip121',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field60' => array( 'field' => 'dip120',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field59' => array( 'field' => 'dip119',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field58' => array( 'field' => 'dip118',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field57' => array( 'field' => 'dip117',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field56' => array( 'field' => 'dip116',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field55' => array( 'field' => 'dip115',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field54' => array( 'field' => 'dip114',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field53' => array( 'field' => 'dip113',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field52' => array( 'field' => 'dip112',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field51' => array( 'field' => 'dip111',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field50' => array( 'field' => 'dip110',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field49' => array( 'field' => 'dip109',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field48' => array( 'field' => 'dip108',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field47' => array( 'field' => 'dip107',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field46' => array( 'field' => 'dip106',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field45' => array( 'field' => 'dip105',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field44' => array( 'field' => 'dip104',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field43' => array( 'field' => 'dip103',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field42' => array( 'field' => 'dip102',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field41' => array( 'field' => 'dip101',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field40' => array( 'field' => 'dip100',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field39' => array( 'field' => 'dip99',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'dip98',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'dip97',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field36' => array( 'field' => 'dip96',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field35' => array( 'field' => 'dip95',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'dip94',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'dip93',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'dip92',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'dip91',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'dip90',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'dip89',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'dip88',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'dip87',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'dip86',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'dip85',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'dip84',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'dip83',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'dip82',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'dip81',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'dip80',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'dip79',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'dip78',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'dip77',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'dip76',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'dip75',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'dip74',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'dip73',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'dip72',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'dip71',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'dip70',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'dip69',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'dip68',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'dip67',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'dip66',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'dip65',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'dip64',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'dip63',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'dip62',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'dip61',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field' => array( 'field' => 'id_urna',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field217' => array( 'field' => 'editado_por',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field218' => array( 'field' => 'fecha_edicion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>