<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_dashboard  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowDashboard"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowDashboard(&$xt, &$templatefile, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

//Alcalde
$alc_escrutada = DBlookup("select round((((select count(*) from voto_alcalde) / count(*)) * 100),1) as Actas_Escrutadas from urna");
$alc_no_escrutado = 100 - $alc_escrutada;

$_SESSION["alc_escrutada"] = $alc_escrutada;
$_SESSION["alc_no_escrutada"] = $alc_no_escrutado;

$xt->assign("alc_escrutada", $_SESSION["alc_escrutada"]);
$xt->assign("alc_no_escrutada", $_SESSION["alc_no_escrutada"]);

//Presidente
$pres_escrutada = DBlookup("select round((((select count(*) from voto_presidente) / count(*)) * 100),1) as Actas_Escrutadas from urna");
$pres_no_escrutado = 100 - $pres_escrutada;

$_SESSION["pres_escrutada"] = $pres_escrutada;
$_SESSION["pres_no_escrutada"] = $pres_no_escrutado;

$xt->assign("pres_escrutada", $_SESSION["pres_escrutada"]);
$xt->assign("pres_no_escrutada", $_SESSION["pres_no_escrutada"]);
;		
} // function BeforeShowDashboard

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		


// dashboatd snippets function

}
?>
