<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_pres___por_distrito  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowReportPrint"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowReportPrint(&$xt, &$templatefile, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

$xt->assign("can1", $_SESSION["can1"]);
$xt->assign("can2", $_SESSION["can2"]);
$xt->assign("can3", $_SESSION["can3"]);
;		
} // function BeforeShowReportPrint

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
