<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_pres___por_distrito  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowReportPrint"]=true;


		$this->events["BeforeShowReport"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowReportPrint(&$xt, &$templatefile, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

$xt->assign("can1", $_SESSION["can1"]);
$xt->assign("can2", $_SESSION["can2"]);
$xt->assign("can3", $_SESSION["can3"]);
$xt->assign("can4", $_SESSION["can4"]);
$xt->assign("can5", $_SESSION["can5"]);
$xt->assign("can6", $_SESSION["can6"]);
$xt->assign("can7", $_SESSION["can7"]);
$xt->assign("can8", $_SESSION["can8"]);
$xt->assign("can9", $_SESSION["can9"]);
$xt->assign("can10", $_SESSION["can10"]);
$xt->assign("can11", $_SESSION["can11"]);
$xt->assign("can12", $_SESSION["can12"]);
$xt->assign("can13", $_SESSION["can13"]);
$xt->assign("can14", $_SESSION["can14"]);
$xt->assign("can15", $_SESSION["can15"]);
$xt->assign("otros", $_SESSION["otros"]);
;		
} // function BeforeShowReportPrint

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowReport(&$xt, &$templatefile, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$xt->assign("can1", $_SESSION["can1"]);
$xt->assign("can2", $_SESSION["can2"]);
$xt->assign("can3", $_SESSION["can3"]);
$xt->assign("can4", $_SESSION["can4"]);
$xt->assign("can5", $_SESSION["can5"]);
$xt->assign("can6", $_SESSION["can6"]);
$xt->assign("can7", $_SESSION["can7"]);
$xt->assign("can8", $_SESSION["can8"]);
$xt->assign("can9", $_SESSION["can9"]);
$xt->assign("can10", $_SESSION["can10"]);
$xt->assign("can11", $_SESSION["can11"]);
$xt->assign("can12", $_SESSION["can12"]);
$xt->assign("can13", $_SESSION["can13"]);
$xt->assign("can14", $_SESSION["can14"]);
$xt->assign("can15", $_SESSION["can15"]);
$xt->assign("otros", $_SESSION["otros"]);
;		
} // function BeforeShowReport

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
